-- Script to populate seat table with data for all schedules
-- This script will add seats for schedules 4, 5, and 6 if they don't already exist

-- Insert seats for Schedule 4 (Train 1) - A1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('A1-W', seat_num), 'A1', b'1', 1, 4
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('A2-W', seat_num), 'A2', b'1', 1, 4
FROM (
         SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
         UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
         UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
         UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
     ) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 4 (Train 1) - B1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('B1-W', seat_num), 'B1', b'1', 1, 4
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 4 (Train 1) - C1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('C1-W', seat_num), 'C1', b'1', 1, 4
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 5 (Train 2) - A1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('A1-W', seat_num), 'A1', b'1', 2, 5
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 5 (Train 2) - B1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('B1-W', seat_num), 'B1', b'1', 2, 5
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 5 (Train 2) - C1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('C1-W', seat_num), 'C1', b'1', 2, 5
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 6 (Train 3) - A1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('A1-W', seat_num), 'A1', b'1', 3, 6
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 6 (Train 3) - B1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('B1-W', seat_num), 'B1', b'1', 3, 6
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Insert seats for Schedule 6 (Train 3) - C1 Coach (20 seats)
INSERT IGNORE INTO seat (seat_number, coach_num, available, train_id, schedule_id)
SELECT CONCAT('C1-W', seat_num), 'C1', b'1', 3, 6
FROM (
    SELECT 1 AS seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS seat_numbers
ORDER BY seat_num;

-- Verify the data was inserted
SELECT 
    schedule_id,
    coach_num,
    COUNT(*) as seat_count,
    SUM(CASE WHEN available = 1 THEN 1 ELSE 0 END) as available_seats
FROM seat 
WHERE schedule_id IN (4, 5, 6)
GROUP BY schedule_id, coach_num
ORDER BY schedule_id, coach_num;
